apiVersion: v1
kind: Service
metadata:
  name: onetimesecret-service
spec:
  selector:
    app: onetimesecret
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30211
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort