apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
        - name: app
          image: registry.1webhost.xyz/onetimesecret:latest
          env:
            - name: ONETIMESECRET_REDIS_URL
              value: redis://onetimesecret-service.default.svc.cluster.local:6379 # Var tvungen anv채nda FQDN (<service-name>.<namespace>.svc.cluster.local) d책 kube-dns v채grade anv채nda sig av alias "redis".
            - name: ONETIMESECRET_SSL
              value: "true"
            - name: ONETIMESECRET_SECRET
              value: 1234567890123456789012345678901234567890123456789012345678901234
            - name: ONETIMESECRET_HOST
              value: onetimesecret.domain.tld
          ports:
            - containerPort: 3000
        - name: redis
          image: redis:7.0-alpine
          env:
            - name: REDIS_PASSWORD
              value: CHANGEME
      imagePullSecrets:
      - name: regcred
