# Dina registry credentials för att kunna hämta image från ditt registry. Måste vara i json-format som sedan base64 encodas.
apiVersion: v1
data:
  .dockerconfigjson: BASE64encodedAuth==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
